# Generated by Django 4.2.7 on 2025-10-01 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=20, unique=True)),
                ('faculty_type', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('visiting_faculty', 'Visiting Faculty'), ('adjunct', 'Adjunct Faculty')], max_length=30)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('sabbatical', 'Sabbatical'), ('retired', 'Retired'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('hire_date', models.DateField()),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('office_hours', models.TextField(blank=True)),
                ('research_interests', models.TextField(blank=True)),
                ('qualifications', models.TextField()),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='students.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('research_type', models.CharField(choices=[('publication', 'Publication'), ('conference', 'Conference'), ('project', 'Research Project'), ('grant', 'Grant'), ('patent', 'Patent'), ('book', 'Book')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('published', 'Published'), ('submitted', 'Submitted'), ('under_review', 'Under Review')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('collaborators', models.TextField(blank=True)),
                ('funding_agency', models.CharField(blank=True, max_length=100)),
                ('funding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('publication_venue', models.CharField(blank=True, max_length=200)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('document', models.FileField(blank=True, null=True, upload_to='research_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_works', to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('vacation', 'Vacation'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('sabbatical', 'Sabbatical'), ('emergency', 'Emergency Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='faculty.faculty')),
                ('substitute_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_assignments', to='faculty.facultyleave')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('student_feedback', 'Student Feedback'), ('peer_review', 'Peer Review'), ('self_assessment', 'Self Assessment'), ('administrative_review', 'Administrative Review')], max_length=30)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=10)),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('teaching_effectiveness', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('research_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('service_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('comments', models.TextField(blank=True)),
                ('evaluation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.course')),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=10)),
                ('teaching_hours_per_week', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('research_hours_per_week', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('administrative_hours_per_week', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_courses', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('committee_memberships', models.TextField(blank=True)),
                ('administrative_roles', models.TextField(blank=True)),
                ('overload_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overload_compensation', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='faculty.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=10)),
                ('section', models.CharField(default='A', max_length=10)),
                ('student_capacity', models.PositiveIntegerField(default=30)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('schedule', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='students.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='faculty.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'course', 'academic_year', 'semester', 'section')},
            },
        ),
    ]
