# Generated by Django 4.2.7 on 2025-10-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='warden',
        ),
        migrations.RemoveField(
            model_name='hostelallocation',
            name='allocated_by',
        ),
        migrations.RemoveField(
            model_name='hostelallocation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='hostelallocation',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='hostelroom',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hostelroom',
            name='hostel',
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backoffice_fee_payments', to='students.student'),
        ),
        migrations.DeleteModel(
            name='BookIssue',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='HostelAllocation',
        ),
        migrations.DeleteModel(
            name='HostelRoom',
        ),
        migrations.DeleteModel(
            name='LibraryBook',
        ),
    ]
