# Generated by Django 4.2.7 on 2025-10-01 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='admission_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissioncycle'),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.program'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissiontest',
            name='admission_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissioncycle'),
        ),
        migrations.AddField(
            model_name='admissiontest',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.program'),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='admission_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissioncycle'),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requirements', to='students.program'),
        ),
        migrations.AddField(
            model_name='admissionfee',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='admissions.application'),
        ),
        migrations.AlterUniqueTogether(
            name='testregistration',
            unique_together={('application', 'test')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'admission_cycle', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='admissionrequirement',
            unique_together={('program', 'admission_cycle')},
        ),
    ]
