# Generated by Django 4.2.7 on 2025-10-02 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admission_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('not_admitted', 'Not Admitted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='admission_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='admission_decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='admission_letter_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='admission_letter_generated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='first_semester_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='first_semester_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='first_semester_fee_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='first_semester_fee_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
